using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace TypeSharp.Test
{
    internal static class Util
    {
        private static string _declare = $"/* Generated by TypeSharp v{Assembly.LoadFrom("TypeSharp").GetName().Version} */";

        public static void Assert(string tsCode, [CallerMemberName] string methodName = "")
        {
            Xunit.Assert.Equal($"{_declare}\r\n\r\n{File.ReadAllText(Path.Combine($"{methodName}.cs.ts"))}", tsCode);
        }
    }
}
