using System;
using System.IO;
using System.Reflection;

namespace TypeSharp.Test
{
    internal static class TestUtil
    {
        private static readonly Lazy<string> DeclareRowCache = new(() => $"/* Generated by TypeSharp v{Assembly.LoadFrom("TypeSharp").GetName().Version} */");
        public static string DeclareContent => DeclareRowCache.Value;

        public static void Assert(string tsCode, string className, string methodName)
        {
            Xunit.Assert.Equal($"{DeclareContent}\r\n\r\n{File.ReadAllText(Path.Combine($"~{className}", $"{className}.{methodName}.cs.ts"))}", tsCode);
        }
    }
}
