/* Generated by TypeSharp v1.4.3.0 */
import { ApiHelper } from "type-sharp";

export class HomeApi {
    constructor(public api: ApiHelper = ApiHelper.default) { }
    index(): Promise<any> { return this.api.get('/Home/Index', {}); }
    privacy(): Promise<any> { return this.api.get('/Home/Privacy', {}); }
    simpleJSend(): Promise<Ajax.JSend<any>> { return this.api.get('/Home/SimpleJSend', {}); }
    error(): Promise<any> { return this.api.get('/Home/Error', {}); }
}
