/* Generated by TypeSharp v1.3.13.0 */
import { ApiHelper } from "../npm-clone";

export class HomeApi {
    constructor(public api: ApiHelper = ApiHelper.default) { }
    index(): Promise<any> { return this.api.get('/Home/Index', {}); }
    privacy(): Promise<any> { return this.api.get('/Home/Privacy', {}); }
    getContent(): Promise<string> { return this.api.get('/Home/GetContent', {}); }
    getContent500(): Promise<string> { return this.api.get('/Home/GetContent500', {}); }
    getFile(): Promise<void> { return this.api.get_save('/Home/GetFile', {}); }
    getFile404(): Promise<void> { return this.api.get_save('/Home/GetFile404', {}); }
    getFile500(): Promise<void> { return this.api.get_save('/Home/GetFile500', {}); }
    error(): Promise<any> { return this.api.get('/Home/Error', {}); }
}
