using static TypeSharp.Test.ModelTests;

namespace TypeSharp.Test;

public class ModelTests
{
    public enum HttpStatus
    {
        None,
        OK = 200,
        NotFound = 404,
    }

    public class NormalModel
    {
        public Guid Guid { get; set; }
        public int Int { get; set; }
        public string Str { get; set; }
        public object Obj { get; set; }
        public HttpStatus Status { get; set; }
    }

    public class NullableModel
    {
        public Guid? Guid { get; set; }
        public int? Int { get; set; }
        public string? Str { get; set; }
        public object? Obj { get; set; }
        public HttpStatus? Status { get; set; }
    }

    public class RequiredModel
    {
        public required Guid Guid { get; set; }
        public required int Int { get; set; }
        public required string Str { get; set; }
        public required object Obj { get; set; }
        public required HttpStatus Status { get; set; }
    }

    public class RequiredNullableModel
    {
        public required Guid? Guid { get; set; }
        public required int? Int { get; set; }
        public required string Str { get; set; }
        public required object? Obj { get; set; }
        public required HttpStatus? Status { get; set; }
        public Generic<string> G { get; set; }
    }

    public class Generic<T>
    {
        public required T Value { get; set; }
    }

    public class GenericModel
    {
        public required Generic<string> GenericString { get; set; }
        public required Generic<Guid> GenericGuid { get; set; }
    }

    [Fact]
    public void Test()
    {
        var _generator = new TypeScriptGenerator(new()
        {
            CamelCase = true,
            //DetectionMode = DetectionMode.AutoDetect,
        })
        {
            //typeof(NormalModel),
            //typeof(NullableModel),
            //typeof(RequiredModel),
            //typeof(RequiredNullableModel),
            typeof(GenericModel)
        };
        var code = _generator.GetCode();
        var expected = """
/* Generated by TypeSharpV3 dev-version */
export enum HttpStatus {
  None = 0,
  OK = 200,
  NotFound = 404
}
export interface NormalModel {
  int: number;
  str?: string;
  obj?: any;
  status: HttpStatus;
}
export interface NullableModel {
  int?: number;
  str?: string;
  obj?: any;
  status?: HttpStatus;
}
export interface RequiredModel {
  int: number;
  str: string;
  obj: any;
  status: HttpStatus;
}
export interface RequiredNullableModel {
  int: number;
  str: string;
  obj: any;
  status: HttpStatus;
}
""";
        Assert.Equal(expected, code);
    }
}
