/* Generated by TypeSharp v1.3.17.0 */

declare namespace TypeSharp.React.Models {
    interface RenderModel {
        area?: string;
        controller?: string;
        action?: string;
        tag?: string;
    }
    export const enum RenderModel_names {
        area = 'Area',
        controller = 'Controller',
        action = 'Action',
        tag = 'Tag',
    }
}
declare namespace Ajax {
    interface JSend<TData> {
        status?: string;
        data?: TData;
        exData?: any;
        message?: string;
        code?: string;
    }
    export const enum JSend_names {
        status = 'status',
        data = 'data',
        exData = 'exData',
        message = 'message',
        code = 'code',
    }
}
