using Ajax;
using System;
using System.IO;
using System.Reflection;
using Xunit;

namespace TypeSharp.Test
{
    public class TypeScriptApiBuilderTests
    {
        private static readonly Version AssemblyVersion = Assembly.LoadFrom("TypeSharp").GetName().Version;

        private string GetExpectedCode(string name)
        {
            return $"/* Generated by TypeSharp v{AssemblyVersion} */\r\n{File.ReadAllText($"{name}.ts")}";
        }

        [Fact]
        public void ApiBuildTest()
        {
            var builder = new TypeScriptApiBuilder("");
            builder.CacheType<SimpleController>();

            var tscode = builder.Compile();
            var expectedCode = GetExpectedCode(nameof(ApiBuildTest));
            Assert.Equal(expectedCode, tscode);
        }

    }
}
