using System.Reflection;

namespace TypeSharp
{
    public class BuildOptions
    {
        public static readonly string VersionDeclaring = $"/* Generated by TypeSharp v{Assembly.GetExecutingAssembly().GetName().Version} */";

        public bool OutputNames = false;
    }
}
