using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;

namespace TypeSharp
{
    internal class Declare
    {
        public static readonly string Info = $"/* Generated by TypeSharp v{Assembly.GetExecutingAssembly().GetName().Version} */";

    }
}
