using System.Reflection;

namespace TypeSharp
{
    internal class Declare
    {
        public static readonly string Info = $"/* Generated by TypeSharp v{Assembly.GetExecutingAssembly().GetName().Version} */";

    }
}
