using DotNetCli;
using System;
using System.Reflection;

namespace TypeSharp.Cli.Test
{
    internal static class TestUtil
    {
        private static readonly Lazy<string> DeclareRowCache = new(() => $"/* Generated by TypeSharp v{Assembly.LoadFrom("TypeSharp").GetName().Version} */");
        public static string DeclareContent => DeclareRowCache.Value;
        public static CmdContainer DefaultCmdContainer => Program.CmdContainer;

        static TestUtil()
        {
            var assembly = Assembly.GetAssembly(typeof(Program));
            var project = ProjectInfo.Get("../../..");
            Program.CmdContainer = new CmdContainer("cli", project);
            DefaultCmdContainer.CacheCommands(assembly);
        }

    }
}
