using DotNetCli;
using System;
using System.Reflection;

namespace TypeSharp.Cli.Test
{
    internal static class TestUtil
    {
        private static readonly Lazy<string> DeclareRowCache = new(() => $"/* Generated by TypeSharp v{Assembly.LoadFrom("TypeSharp").GetName().Version} */");
        public static string DeclareContent => DeclareRowCache.Value;

    }
}
