/* Generated by TypeSharp v1.3.17.0 */

declare namespace TypeSharp.Test {
    interface SimpleModel {
        value?: number;
        lazyInt32?: number;
        lazyInt64?: any;
        dateTimeValue?: Date;
    }
}
